development:
  adapter: mysql
  database: 
  username: 
  password:
  encoding: utf8
  
test:
  adapter: mysql
  database: 
  username: 
  password:
  socket: /tmp/mysql.sock
  encoding: utf8
  
production:
  adapter: mysql
  database: 
  username: 
  password:
  encoding: utf8
  
staging:
  adapter: mysql
  database: 
  username: 
  password:
  encoding: utf8

