development:
  # Sqlite Settings
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000
  
test:
  # Sqlite Settings
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000
    
staging:
  adapter: mysql
  database: 
  username: 
  password:
  encoding: utf8

production:
  adapter: mysql
  database: 
  username: 
  password:
  encoding: utf8

