development:
  adapter: mysql
  database: cnn-airport-dev
  username: root
  password:
  encoding: utf8
  
test:
  adapter: mysql
  database: cnn-airport-test
  username: root
  password:
  socket: /tmp/mysql.sock
  encoding: utf8
  
production:
  adapter: mysql
  database: cnn-airport-prod
  username: root
  password:
  encoding: utf8
  
staging:
  adapter: mysql
  database: cnn-airport-stage
  username: root
  password:
  encoding: utf8

cucumber:
  <<: *TEST